global using System.Diagnostics;
global using Clock;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Pure.DI;
global using Pure.DI.MS;
global using WebApp;
global using WebApp.Controllers;
global using static Pure.DI.Lifetime;